{"p.add16"      , 0, {"I",0}, "d,s,t", MATCH_P_ADD16  , MASK_P_ADD16   , match_opcode, 0},
{"p.radd16"     , 0, {"I",0}, "d,s,t", MATCH_P_RADD16 , MASK_P_RADD16  , match_opcode, 0},
{"p.uradd16"    , 0, {"I",0}, "d,s,t", MATCH_P_URADD16, MASK_P_URADD16 , match_opcode, 0},
{"p.kadd16"     , 0, {"I",0}, "d,s,t", MATCH_P_KADD16 , MASK_P_KADD16  , match_opcode, 0},
{"p.ukadd16"    , 0, {"I",0}, "d,s,t", MATCH_P_UKADD16, MASK_P_UKADD16 , match_opcode, 0},
{"p.sub16"      , 0, {"I",0}, "d,s,t", MATCH_P_SUB16  , MASK_P_SUB16   , match_opcode, 0},
{"p.rsub16"     , 0, {"I",0}, "d,s,t", MATCH_P_RSUB16 , MASK_P_RSUB16  , match_opcode, 0},
{"p.ursub16"    , 0, {"I",0}, "d,s,t", MATCH_P_URSUB16, MASK_P_URSUB16 , match_opcode, 0},
{"p.ksub16"     , 0, {"I",0}, "d,s,t", MATCH_P_KSUB16 , MASK_P_KSUB16  , match_opcode, 0},
{"p.uksub16"    , 0, {"I",0}, "d,s,t", MATCH_P_UKSUB16, MASK_P_UKSUB16 , match_opcode, 0},
{"p.cras16"     , 0, {"I",0}, "d,s,t", MATCH_P_CRAS16 , MASK_P_CRAS16  , match_opcode, 0},
{"p.rcras16"    , 0, {"I",0}, "d,s,t", MATCH_P_RCRAS16, MASK_P_RCRAS16 , match_opcode, 0},
{"p.urcras16"   , 0, {"I",0}, "d,s,t", MATCH_P_URCRAS16, MASK_P_URCRAS16, match_opcode, 0},
{"p.kcras16"    , 0, {"I",0}, "d,s,t", MATCH_P_KCRAS16, MASK_P_KCRAS16 , match_opcode, 0},
{"p.ukcras16"   , 0, {"I",0}, "d,s,t", MATCH_P_UKCRAS16, MASK_P_UKCRAS16, match_opcode, 0},
{"p.crsa16"     , 0, {"I",0}, "d,s,t", MATCH_P_CRSA16 , MASK_P_CRSA16  , match_opcode, 0},
{"p.rcrsa16"    , 0, {"I",0}, "d,s,t", MATCH_P_RCRSA16, MASK_P_RCRSA16 , match_opcode, 0},
{"p.urcrsa16"   , 0, {"I",0}, "d,s,t", MATCH_P_URCRSA16, MASK_P_URCRSA16, match_opcode, 0},
{"p.kcrsa16"    , 0, {"I",0}, "d,s,t", MATCH_P_KCRSA16, MASK_P_KCRSA16 , match_opcode, 0},
{"p.ukcrsa16"   , 0, {"I",0}, "d,s,t", MATCH_P_UKCRSA16, MASK_P_UKCRSA16, match_opcode, 0},
{"p.stas16"     , 0, {"I",0}, "d,s,t", MATCH_P_STAS16 , MASK_P_STAS16  , match_opcode, 0},
{"p.rstas16"    , 0, {"I",0}, "d,s,t", MATCH_P_RSTAS16, MASK_P_RSTAS16 , match_opcode, 0},
{"p.urstas16"   , 0, {"I",0}, "d,s,t", MATCH_P_URSTAS16, MASK_P_URSTAS16, match_opcode, 0},
{"p.kstas16"    , 0, {"I",0}, "d,s,t", MATCH_P_KSTAS16, MASK_P_KSTAS16 , match_opcode, 0},
{"p.ukstas16"   , 0, {"I",0}, "d,s,t", MATCH_P_UKSTAS16, MASK_P_UKSTAS16, match_opcode, 0},
{"p.stsa16"     , 0, {"I",0}, "d,s,t", MATCH_P_STSA16 , MASK_P_STSA16  , match_opcode, 0},
{"p.rstsa16"    , 0, {"I",0}, "d,s,t", MATCH_P_RSTSA16, MASK_P_RSTSA16 , match_opcode, 0},
{"p.urstsa16"   , 0, {"I",0}, "d,s,t", MATCH_P_URSTSA16, MASK_P_URSTSA16, match_opcode, 0},
{"p.kstsa16"    , 0, {"I",0}, "d,s,t", MATCH_P_KSTSA16, MASK_P_KSTSA16 , match_opcode, 0},
{"p.ukstsa16"   , 0, {"I",0}, "d,s,t", MATCH_P_UKSTSA16, MASK_P_UKSTSA16, match_opcode, 0},
{"p.add8"       , 0, {"I",0}, "d,s,t", MATCH_P_ADD8   , MASK_P_ADD8    , match_opcode, 0},
{"p.radd8"      , 0, {"I",0}, "d,s,t", MATCH_P_RADD8  , MASK_P_RADD8   , match_opcode, 0},
{"p.uradd8"     , 0, {"I",0}, "d,s,t", MATCH_P_URADD8 , MASK_P_URADD8  , match_opcode, 0},
{"p.kadd8"      , 0, {"I",0}, "d,s,t", MATCH_P_KADD8  , MASK_P_KADD8   , match_opcode, 0},
{"p.ukadd8"     , 0, {"I",0}, "d,s,t", MATCH_P_UKADD8 , MASK_P_UKADD8  , match_opcode, 0},
{"p.sub8"       , 0, {"I",0}, "d,s,t", MATCH_P_SUB8   , MASK_P_SUB8    , match_opcode, 0},
{"p.rsub8"      , 0, {"I",0}, "d,s,t", MATCH_P_RSUB8  , MASK_P_RSUB8   , match_opcode, 0},
{"p.ursub8"     , 0, {"I",0}, "d,s,t", MATCH_P_URSUB8 , MASK_P_URSUB8  , match_opcode, 0},
{"p.ksub8"      , 0, {"I",0}, "d,s,t", MATCH_P_KSUB8  , MASK_P_KSUB8   , match_opcode, 0},
{"p.uksub8"     , 0, {"I",0}, "d,s,t", MATCH_P_UKSUB8 , MASK_P_UKSUB8  , match_opcode, 0},
{"p.sra16"      , 0, {"I",0}, "d,s,t", MATCH_P_SRA16  , MASK_P_SRA16   , match_opcode, 0},
{"p.srai16"     , 0, {"I",0}, "d,s,i4", MATCH_P_SRAI16 , MASK_P_SRAI16  , match_opcode, 0},
{"p.sra16.u"    , 0, {"I",0}, "d,s,t", MATCH_P_SRA16_U, MASK_P_SRA16_U , match_opcode, 0},
{"p.srai16.u"   , 0, {"I",0}, "d,s,i4", MATCH_P_SRAI16_U, MASK_P_SRAI16_U, match_opcode, 0},
{"p.srl16"      , 0, {"I",0}, "d,s,t", MATCH_P_SRL16  , MASK_P_SRL16   , match_opcode, 0},
{"p.srli16"     , 0, {"I",0}, "d,s,i4", MATCH_P_SRLI16 , MASK_P_SRLI16  , match_opcode, 0},
{"p.srl16.u"    , 0, {"I",0}, "d,s,t", MATCH_P_SRL16_U, MASK_P_SRL16_U , match_opcode, 0},
{"p.srli16.u"   , 0, {"I",0}, "d,s,i4", MATCH_P_SRLI16_U, MASK_P_SRLI16_U, match_opcode, 0},
{"p.sll16"      , 0, {"I",0}, "d,s,t", MATCH_P_SLL16  , MASK_P_SLL16   , match_opcode, 0},
{"p.slli16"     , 0, {"I",0}, "d,s,i4", MATCH_P_SLLI16 , MASK_P_SLLI16  , match_opcode, 0},
{"p.ksll16"     , 0, {"I",0}, "d,s,t", MATCH_P_KSLL16 , MASK_P_KSLL16  , match_opcode, 0},
{"p.kslli16"    , 0, {"I",0}, "d,s,i4", MATCH_P_KSLLI16, MASK_P_KSLLI16 , match_opcode, 0},
{"p.kslra16"    , 0, {"I",0}, "d,s,t", MATCH_P_KSLRA16, MASK_P_KSLRA16 , match_opcode, 0},
{"p.kslra16.u"  , 0, {"I",0}, "d,s,t", MATCH_P_KSLRA16_U, MASK_P_KSLRA16_U, match_opcode, 0},
{"p.sra8"       , 0, {"I",0}, "d,s,t", MATCH_P_SRA8   , MASK_P_SRA8    , match_opcode, 0},
{"p.srai8"      , 0, {"I",0}, "d,s,i3", MATCH_P_SRAI8  , MASK_P_SRAI8   , match_opcode, 0},
{"p.sra8.u"     , 0, {"I",0}, "d,s,t", MATCH_P_SRA8_U , MASK_P_SRA8_U  , match_opcode, 0},
{"p.srai8.u"    , 0, {"I",0}, "d,s,i3", MATCH_P_SRAI8_U, MASK_P_SRAI8_U , match_opcode, 0},
{"p.srl8"       , 0, {"I",0}, "d,s,t", MATCH_P_SRL8   , MASK_P_SRL8    , match_opcode, 0},
{"p.srli8"      , 0, {"I",0}, "d,s,i3", MATCH_P_SRLI8  , MASK_P_SRLI8   , match_opcode, 0},
{"p.srl8.u"     , 0, {"I",0}, "d,s,t", MATCH_P_SRL8_U , MASK_P_SRL8_U  , match_opcode, 0},
{"p.srli8.u"    , 0, {"I",0}, "d,s,i3", MATCH_P_SRLI8_U, MASK_P_SRLI8_U , match_opcode, 0},
{"p.sll8"       , 0, {"I",0}, "d,s,t", MATCH_P_SLL8   , MASK_P_SLL8    , match_opcode, 0},
{"p.slli8"      , 0, {"I",0}, "d,s,i3", MATCH_P_SLLI8  , MASK_P_SLLI8   , match_opcode, 0},
{"p.ksll8"      , 0, {"I",0}, "d,s,t", MATCH_P_KSLL8  , MASK_P_KSLL8   , match_opcode, 0},
{"p.kslli8"     , 0, {"I",0}, "d,s,i3", MATCH_P_KSLLI8 , MASK_P_KSLLI8  , match_opcode, 0},
{"p.kslra8"     , 0, {"I",0}, "d,s,t", MATCH_P_KSLRA8 , MASK_P_KSLRA8  , match_opcode, 0},
{"p.kslra8.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KSLRA8_U, MASK_P_KSLRA8_U, match_opcode, 0},
{"p.cmpeq16"    , 0, {"I",0}, "d,s,t", MATCH_P_CMPEQ16, MASK_P_CMPEQ16 , match_opcode, 0},
{"p.scmplt16"   , 0, {"I",0}, "d,s,t", MATCH_P_SCMPLT16, MASK_P_SCMPLT16, match_opcode, 0},
{"p.scmple16"   , 0, {"I",0}, "d,s,t", MATCH_P_SCMPLE16, MASK_P_SCMPLE16, match_opcode, 0},
{"p.ucmplt16"   , 0, {"I",0}, "d,s,t", MATCH_P_UCMPLT16, MASK_P_UCMPLT16, match_opcode, 0},
{"p.ucmple16"   , 0, {"I",0}, "d,s,t", MATCH_P_UCMPLE16, MASK_P_UCMPLE16, match_opcode, 0},
{"p.cmpeq8"     , 0, {"I",0}, "d,s,t", MATCH_P_CMPEQ8 , MASK_P_CMPEQ8  , match_opcode, 0},
{"p.scmplt8"    , 0, {"I",0}, "d,s,t", MATCH_P_SCMPLT8, MASK_P_SCMPLT8 , match_opcode, 0},
{"p.scmple8"    , 0, {"I",0}, "d,s,t", MATCH_P_SCMPLE8, MASK_P_SCMPLE8 , match_opcode, 0},
{"p.ucmplt8"    , 0, {"I",0}, "d,s,t", MATCH_P_UCMPLT8, MASK_P_UCMPLT8 , match_opcode, 0},
{"p.ucmple8"    , 0, {"I",0}, "d,s,t", MATCH_P_UCMPLE8, MASK_P_UCMPLE8 , match_opcode, 0},
{"p.smul16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMUL16 , MASK_P_SMUL16  , match_opcode, 0},
{"p.smulx16"    , 0, {"I",0}, "d,s,t", MATCH_P_SMULX16, MASK_P_SMULX16 , match_opcode, 0},
{"p.khm16"      , 0, {"I",0}, "d,s,t", MATCH_P_KHM16  , MASK_P_KHM16   , match_opcode, 0},
{"p.khmx16"     , 0, {"I",0}, "d,s,t", MATCH_P_KHMX16 , MASK_P_KHMX16  , match_opcode, 0},
{"p.smul8"      , 0, {"I",0}, "d,s,t", MATCH_P_SMUL8  , MASK_P_SMUL8   , match_opcode, 0},
{"p.smulx8"     , 0, {"I",0}, "d,s,t", MATCH_P_SMULX8 , MASK_P_SMULX8  , match_opcode, 0},
{"p.khm8"       , 0, {"I",0}, "d,s,t", MATCH_P_KHM8   , MASK_P_KHM8    , match_opcode, 0},
{"p.khmx8"      , 0, {"I",0}, "d,s,t", MATCH_P_KHMX8  , MASK_P_KHMX8   , match_opcode, 0},
{"p.smin16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMIN16 , MASK_P_SMIN16  , match_opcode, 0},
{"p.umin16"     , 0, {"I",0}, "d,s,t", MATCH_P_UMIN16 , MASK_P_UMIN16  , match_opcode, 0},
{"p.smax16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMAX16 , MASK_P_SMAX16  , match_opcode, 0},
{"p.umax16"     , 0, {"I",0}, "d,s,t", MATCH_P_UMAX16 , MASK_P_UMAX16  , match_opcode, 0},
{"p.sclip16"    , 0, {"I",0}, "d,s,i4", MATCH_P_SCLIP16, MASK_P_SCLIP16 , match_opcode, 0},
{"p.uclip16"    , 0, {"I",0}, "d,s,i4", MATCH_P_UCLIP16, MASK_P_UCLIP16 , match_opcode, 0},
{"p.kabs16"     , 0, {"I",0}, "d,s", MATCH_P_KABS16 , MASK_P_KABS16  , match_opcode, 0},
{"p.clrs16"     , 0, {"I",0}, "d,s", MATCH_P_CLRS16 , MASK_P_CLRS16  , match_opcode, 0},
{"p.clz16"      , 0, {"I",0}, "d,s", MATCH_P_CLZ16  , MASK_P_CLZ16   , match_opcode, 0},
{"p.clo16"      , 0, {"I",0}, "d,s", MATCH_P_CLO16  , MASK_P_CLO16   , match_opcode, 0},
{"p.smin8"      , 0, {"I",0}, "d,s,t", MATCH_P_SMIN8  , MASK_P_SMIN8   , match_opcode, 0},
{"p.umin8"      , 0, {"I",0}, "d,s,t", MATCH_P_UMIN8  , MASK_P_UMIN8   , match_opcode, 0},
{"p.smax8"      , 0, {"I",0}, "d,s,t", MATCH_P_SMAX8  , MASK_P_SMAX8   , match_opcode, 0},
{"p.umax8"      , 0, {"I",0}, "d,s,t", MATCH_P_UMAX8  , MASK_P_UMAX8   , match_opcode, 0},
{"p.sclip8"     , 0, {"I",0}, "d,s,i3", MATCH_P_SCLIP8 , MASK_P_SCLIP8  , match_opcode, 0},
{"p.uclip8"     , 0, {"I",0}, "d,s,i3", MATCH_P_UCLIP8 , MASK_P_UCLIP8  , match_opcode, 0},
{"p.kabs8"      , 0, {"I",0}, "d,s", MATCH_P_KABS8  , MASK_P_KABS8   , match_opcode, 0},
{"p.clrs8"      , 0, {"I",0}, "d,s", MATCH_P_CLRS8  , MASK_P_CLRS8   , match_opcode, 0},
{"p.clz8"       , 0, {"I",0}, "d,s", MATCH_P_CLZ8   , MASK_P_CLZ8    , match_opcode, 0},
{"p.clo8"       , 0, {"I",0}, "d,s", MATCH_P_CLO8   , MASK_P_CLO8    , match_opcode, 0},
{"p.sunpkd8_10" , 0, {"I",0}, "d,s", MATCH_P_SUNPKD8_10, MASK_P_SUNPKD8_10, match_opcode, 0},
{"p.sunpkd8_20" , 0, {"I",0}, "d,s", MATCH_P_SUNPKD8_20, MASK_P_SUNPKD8_20, match_opcode, 0},
{"p.sunpkd8_30" , 0, {"I",0}, "d,s", MATCH_P_SUNPKD8_30, MASK_P_SUNPKD8_30, match_opcode, 0},
{"p.sunpkd8_31" , 0, {"I",0}, "d,s", MATCH_P_SUNPKD8_31, MASK_P_SUNPKD8_31, match_opcode, 0},
{"p.sunpkd8_32" , 0, {"I",0}, "d,s", MATCH_P_SUNPKD8_32, MASK_P_SUNPKD8_32, match_opcode, 0},
{"p.zunpkd8_10" , 0, {"I",0}, "d,s", MATCH_P_ZUNPKD8_10, MASK_P_ZUNPKD8_10, match_opcode, 0},
{"p.zunpkd8_20" , 0, {"I",0}, "d,s", MATCH_P_ZUNPKD8_20, MASK_P_ZUNPKD8_20, match_opcode, 0},
{"p.zunpkd8_30" , 0, {"I",0}, "d,s", MATCH_P_ZUNPKD8_30, MASK_P_ZUNPKD8_30, match_opcode, 0},
{"p.zunpkd8_31" , 0, {"I",0}, "d,s", MATCH_P_ZUNPKD8_31, MASK_P_ZUNPKD8_31, match_opcode, 0},
{"p.zunpkd8_32" , 0, {"I",0}, "d,s", MATCH_P_ZUNPKD8_32, MASK_P_ZUNPKD8_32, match_opcode, 0},
{"p.pkbb16"     , 0, {"I",0}, "d,s,t", MATCH_P_PKBB16 , MASK_P_PKBB16  , match_opcode, 0},
{"p.pkbt16"     , 0, {"I",0}, "d,s,t", MATCH_P_PKBT16 , MASK_P_PKBT16  , match_opcode, 0},
{"p.pktb16"     , 0, {"I",0}, "d,s,t", MATCH_P_PKTB16 , MASK_P_PKTB16  , match_opcode, 0},
{"p.pktt16"     , 0, {"I",0}, "d,s,t", MATCH_P_PKTT16 , MASK_P_PKTT16  , match_opcode, 0},
{"p.smmul"      , 0, {"I",0}, "d,s,t", MATCH_P_SMMUL  , MASK_P_SMMUL   , match_opcode, 0},
{"p.smmul.u"    , 0, {"I",0}, "d,s,t", MATCH_P_SMMUL_U, MASK_P_SMMUL_U , match_opcode, 0},
{"p.kmmac"      , 0, {"I",0}, "d,s,t", MATCH_P_KMMAC  , MASK_P_KMMAC   , match_opcode, 0},
{"p.kmmac.u"    , 0, {"I",0}, "d,s,t", MATCH_P_KMMAC_U, MASK_P_KMMAC_U , match_opcode, 0},
{"p.kmmsb"      , 0, {"I",0}, "d,s,t", MATCH_P_KMMSB  , MASK_P_KMMSB   , match_opcode, 0},
{"p.kmmsb.u"    , 0, {"I",0}, "d,s,t", MATCH_P_KMMSB_U, MASK_P_KMMSB_U , match_opcode, 0},
{"p.kwmmul"     , 0, {"I",0}, "d,s,t", MATCH_P_KWMMUL , MASK_P_KWMMUL  , match_opcode, 0},
{"p.kwmmul.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KWMMUL_U, MASK_P_KWMMUL_U, match_opcode, 0},
{"p.smmwb"      , 0, {"I",0}, "d,s,t", MATCH_P_SMMWB  , MASK_P_SMMWB   , match_opcode, 0},
{"p.smmwb.u"    , 0, {"I",0}, "d,s,t", MATCH_P_SMMWB_U, MASK_P_SMMWB_U , match_opcode, 0},
{"p.smmwt"      , 0, {"I",0}, "d,s,t", MATCH_P_SMMWT  , MASK_P_SMMWT   , match_opcode, 0},
{"p.smmwt.u"    , 0, {"I",0}, "d,s,t", MATCH_P_SMMWT_U, MASK_P_SMMWT_U , match_opcode, 0},
{"p.kmmawb"     , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWB , MASK_P_KMMAWB  , match_opcode, 0},
{"p.kmmawb.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWB_U, MASK_P_KMMAWB_U, match_opcode, 0},
{"p.kmmawt"     , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWT , MASK_P_KMMAWT  , match_opcode, 0},
{"p.kmmawt.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWT_U, MASK_P_KMMAWT_U, match_opcode, 0},
{"p.kmmwb2"     , 0, {"I",0}, "d,s,t", MATCH_P_KMMWB2 , MASK_P_KMMWB2  , match_opcode, 0},
{"p.kmmwb2.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KMMWB2_U, MASK_P_KMMWB2_U, match_opcode, 0},
{"p.kmmwt2"     , 0, {"I",0}, "d,s,t", MATCH_P_KMMWT2 , MASK_P_KMMWT2  , match_opcode, 0},
{"p.kmmwt2.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KMMWT2_U, MASK_P_KMMWT2_U, match_opcode, 0},
{"p.kmmawb2"    , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWB2, MASK_P_KMMAWB2 , match_opcode, 0},
{"p.kmmawb2.u"  , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWB2_U, MASK_P_KMMAWB2_U, match_opcode, 0},
{"p.kmmawt2"    , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWT2, MASK_P_KMMAWT2 , match_opcode, 0},
{"p.kmmawt2.u"  , 0, {"I",0}, "d,s,t", MATCH_P_KMMAWT2_U, MASK_P_KMMAWT2_U, match_opcode, 0},
{"p.smslda"     , 0, {"I",0}, "d,s,t", MATCH_P_SMSLDA , MASK_P_SMSLDA  , match_opcode, 0},
{"p.smslxda"    , 0, {"I",0}, "d,s,t", MATCH_P_SMSLXDA, MASK_P_SMSLXDA , match_opcode, 0},
{"p.smbb16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMBB16 , MASK_P_SMBB16  , match_opcode, 0},
{"p.smbt16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMBT16 , MASK_P_SMBT16  , match_opcode, 0},
{"p.smtt16"     , 0, {"I",0}, "d,s,t", MATCH_P_SMTT16 , MASK_P_SMTT16  , match_opcode, 0},
{"p.kmda"       , 0, {"I",0}, "d,s,t", MATCH_P_KMDA   , MASK_P_KMDA    , match_opcode, 0},
{"p.kmxda"      , 0, {"I",0}, "d,s,t", MATCH_P_KMXDA  , MASK_P_KMXDA   , match_opcode, 0},
{"p.smds"       , 0, {"I",0}, "d,s,t", MATCH_P_SMDS   , MASK_P_SMDS    , match_opcode, 0},
{"p.smdrs"      , 0, {"I",0}, "d,s,t", MATCH_P_SMDRS  , MASK_P_SMDRS   , match_opcode, 0},
{"p.smxds"      , 0, {"I",0}, "d,s,t", MATCH_P_SMXDS  , MASK_P_SMXDS   , match_opcode, 0},
{"p.kmabb"      , 0, {"I",0}, "d,s,t", MATCH_P_KMABB  , MASK_P_KMABB   , match_opcode, 0},
{"p.kmabt"      , 0, {"I",0}, "d,s,t", MATCH_P_KMABT  , MASK_P_KMABT   , match_opcode, 0},
{"p.kmatt"      , 0, {"I",0}, "d,s,t", MATCH_P_KMATT  , MASK_P_KMATT   , match_opcode, 0},
{"p.kmada"      , 0, {"I",0}, "d,s,t", MATCH_P_KMADA  , MASK_P_KMADA   , match_opcode, 0},
{"p.kmaxda"     , 0, {"I",0}, "d,s,t", MATCH_P_KMAXDA , MASK_P_KMAXDA  , match_opcode, 0},
{"p.kmads"      , 0, {"I",0}, "d,s,t", MATCH_P_KMADS  , MASK_P_KMADS   , match_opcode, 0},
{"p.kmadrs"     , 0, {"I",0}, "d,s,t", MATCH_P_KMADRS , MASK_P_KMADRS  , match_opcode, 0},
{"p.kmaxds"     , 0, {"I",0}, "d,s,t", MATCH_P_KMAXDS , MASK_P_KMAXDS  , match_opcode, 0},
{"p.kmsda"      , 0, {"I",0}, "d,s,t", MATCH_P_KMSDA  , MASK_P_KMSDA   , match_opcode, 0},
{"p.kmsxda"     , 0, {"I",0}, "d,s,t", MATCH_P_KMSXDA , MASK_P_KMSXDA  , match_opcode, 0},
{"p.sclip32"    , 0, {"I",0}, "d,s,i5", MATCH_P_SCLIP32, MASK_P_SCLIP32 , match_opcode, 0},
{"p.uclip32"    , 0, {"I",0}, "d,s,i5", MATCH_P_UCLIP32, MASK_P_UCLIP32 , match_opcode, 0},
{"p.clrs32"     , 0, {"I",0}, "d,s", MATCH_P_CLRS32 , MASK_P_CLRS32  , match_opcode, 0},
{"p.clz32"      , 0, {"I",0}, "d,s", MATCH_P_CLZ32  , MASK_P_CLZ32   , match_opcode, 0},
{"p.clo32"      , 0, {"I",0}, "d,s", MATCH_P_CLO32  , MASK_P_CLO32   , match_opcode, 0},
{"p.pbsad"      , 0, {"I",0}, "d,s,t", MATCH_P_PBSAD  , MASK_P_PBSAD   , match_opcode, 0},
{"p.pbsada"     , 0, {"I",0}, "d,s,t", MATCH_P_PBSADA , MASK_P_PBSADA  , match_opcode, 0},
{"p.smaqa"      , 0, {"I",0}, "d,s,t", MATCH_P_SMAQA  , MASK_P_SMAQA   , match_opcode, 0},
{"p.umaqa"      , 0, {"I",0}, "d,s,t", MATCH_P_UMAQA  , MASK_P_UMAQA   , match_opcode, 0},
{"p.smaqa.su"   , 0, {"I",0}, "d,s,t", MATCH_P_SMAQA_SU, MASK_P_SMAQA_SU, match_opcode, 0},
{"p.kaddh"      , 0, {"I",0}, "d,s,t", MATCH_P_KADDH  , MASK_P_KADDH   , match_opcode, 0},
{"p.ksubh"      , 0, {"I",0}, "d,s,t", MATCH_P_KSUBH  , MASK_P_KSUBH   , match_opcode, 0},
{"p.khmbb"      , 0, {"I",0}, "d,s,t", MATCH_P_KHMBB  , MASK_P_KHMBB   , match_opcode, 0},
{"p.khmbt"      , 0, {"I",0}, "d,s,t", MATCH_P_KHMBT  , MASK_P_KHMBT   , match_opcode, 0},
{"p.khmtt"      , 0, {"I",0}, "d,s,t", MATCH_P_KHMTT  , MASK_P_KHMTT   , match_opcode, 0},
{"p.ukaddh"     , 0, {"I",0}, "d,s,t", MATCH_P_UKADDH , MASK_P_UKADDH  , match_opcode, 0},
{"p.uksubh"     , 0, {"I",0}, "d,s,t", MATCH_P_UKSUBH , MASK_P_UKSUBH  , match_opcode, 0},
{"p.kaddw"      , 0, {"I",0}, "d,s,t", MATCH_P_KADDW  , MASK_P_KADDW   , match_opcode, 0},
{"p.ukaddw"     , 0, {"I",0}, "d,s,t", MATCH_P_UKADDW , MASK_P_UKADDW  , match_opcode, 0},
{"p.ksubw"      , 0, {"I",0}, "d,s,t", MATCH_P_KSUBW  , MASK_P_KSUBW   , match_opcode, 0},
{"p.uksubw"     , 0, {"I",0}, "d,s,t", MATCH_P_UKSUBW , MASK_P_UKSUBW  , match_opcode, 0},
{"p.kdmbb"      , 0, {"I",0}, "d,s,t", MATCH_P_KDMBB  , MASK_P_KDMBB   , match_opcode, 0},
{"p.kdmbt"      , 0, {"I",0}, "d,s,t", MATCH_P_KDMBT  , MASK_P_KDMBT   , match_opcode, 0},
{"p.kdmtt"      , 0, {"I",0}, "d,s,t", MATCH_P_KDMTT  , MASK_P_KDMTT   , match_opcode, 0},
{"p.kslraw"     , 0, {"I",0}, "d,s,t", MATCH_P_KSLRAW , MASK_P_KSLRAW  , match_opcode, 0},
{"p.kslraw.u"   , 0, {"I",0}, "d,s,t", MATCH_P_KSLRAW_U, MASK_P_KSLRAW_U, match_opcode, 0},
{"p.ksllw"      , 0, {"I",0}, "d,s,t", MATCH_P_KSLLW  , MASK_P_KSLLW   , match_opcode, 0},
{"p.ksllwi"     , 0, {"I",0}, "d,s,i5", MATCH_P_KSLLWI , MASK_P_KSLLWI  , match_opcode, 0},
{"p.kdmabb"     , 0, {"I",0}, "d,s,t", MATCH_P_KDMABB , MASK_P_KDMABB  , match_opcode, 0},
{"p.kdmabt"     , 0, {"I",0}, "d,s,t", MATCH_P_KDMABT , MASK_P_KDMABT  , match_opcode, 0},
{"p.kdmatt"     , 0, {"I",0}, "d,s,t", MATCH_P_KDMATT , MASK_P_KDMATT  , match_opcode, 0},
{"p.kabsw"      , 0, {"I",0}, "d,s", MATCH_P_KABSW  , MASK_P_KABSW   , match_opcode, 0},
{"p.raddw"      , 0, {"I",0}, "d,s,t", MATCH_P_RADDW  , MASK_P_RADDW   , match_opcode, 0},
{"p.uraddw"     , 0, {"I",0}, "d,s,t", MATCH_P_URADDW , MASK_P_URADDW  , match_opcode, 0},
{"p.rsubw"      , 0, {"I",0}, "d,s,t", MATCH_P_RSUBW  , MASK_P_RSUBW   , match_opcode, 0},
{"p.ursubw"     , 0, {"I",0}, "d,s,t", MATCH_P_URSUBW , MASK_P_URSUBW  , match_opcode, 0},
//RDOV TODO
//CLROV TODO
{"p.ave"        , 0, {"I",0}, "d,s,t", MATCH_P_AVE    , MASK_P_AVE     , match_opcode, 0},
{"p.sra.u"      , 0, {"I",0}, "d,s,t", MATCH_P_SRA_U  , MASK_P_SRA_U   , match_opcode, 0},
{"p.srai.u"     , 0, {"I",0}, "d,s,i5", MATCH_P_SRAI_U , MASK_P_SRAI_U  , match_opcode, 0},
{"p.bitrev"     , 0, {"I",0}, "d,s,t", MATCH_P_BITREV , MASK_P_BITREV  , match_opcode, 0},
{"p.bitrevi"    , 0, {"I",0}, "d,s,i5", MATCH_P_BITREVI, MASK_P_BITREVI , match_opcode, 0},
{"p.wext"       , 0, {"I",0}, "d,s,t", MATCH_P_WEXT   , MASK_P_WEXT    , match_opcode, 0},
{"p.wexti"      , 0, {"I",0}, "d,s,i5", MATCH_P_WEXTI  , MASK_P_WEXTI   , match_opcode, 0},
{"p.bpick"      , 0, {"I",0}, "d,s,t,ic", MATCH_P_BPICK  , MASK_P_BPICK   , match_opcode, 0},
{"p.maddr32"    , 0, {"I",0}, "d,s,t", MATCH_P_MADDR32, MASK_P_MADDR32 , match_opcode, 0},
{"p.maxw"       , 0, {"I",0}, "d,s,t", MATCH_P_MAXW   , MASK_P_MAXW    , match_opcode, 0},
{"p.minw"       , 0, {"I",0}, "d,s,t", MATCH_P_MINW   , MASK_P_MINW    , match_opcode, 0},
{"p.msubr32"    , 0, {"I",0}, "d,s,t", MATCH_P_MSUBR32, MASK_P_MSUBR32 , match_opcode, 0},
{"p.mulr64"     , 0, {"I",0}, "d,s,t", MATCH_P_MULR64 , MASK_P_MULR64  , match_opcode, 0},
{"p.mulsr64"    , 0, {"I",0}, "d,s,t", MATCH_P_MULSR64, MASK_P_MULSR64 , match_opcode, 0},
{"p.insb"       , 0, {"I",0}, "d,s,i3", MATCH_P_INSB   , MASK_P_INSB    , match_opcode, 0},
{"p.smal"       , 0, {"I",0}, "d,s,t", MATCH_P_SMAL   , MASK_P_SMAL    , match_opcode, 0},
{"p.smalbb"     , 0, {"I",0}, "d,s,t", MATCH_P_SMALBB , MASK_P_SMALBB  , match_opcode, 0},
{"p.smalbt"     , 0, {"I",0}, "d,s,t", MATCH_P_SMALBT , MASK_P_SMALBT  , match_opcode, 0},
{"p.smaltt"     , 0, {"I",0}, "d,s,t", MATCH_P_SMALTT , MASK_P_SMALTT  , match_opcode, 0},
{"p.smalda"     , 0, {"I",0}, "d,s,t", MATCH_P_SMALDA , MASK_P_SMALDA  , match_opcode, 0},
{"p.smalxda"    , 0, {"I",0}, "d,s,t", MATCH_P_SMALXDA, MASK_P_SMALXDA , match_opcode, 0},
{"p.smalds"     , 0, {"I",0}, "d,s,t", MATCH_P_SMALDS , MASK_P_SMALDS  , match_opcode, 0},
{"p.smaldrs"    , 0, {"I",0}, "d,s,t", MATCH_P_SMALDRS, MASK_P_SMALDRS , match_opcode, 0},
{"p.smalxds"    , 0, {"I",0}, "d,s,t", MATCH_P_SMALXDS, MASK_P_SMALXDS , match_opcode, 0},
{"p.smar64"     , 0, {"I",0}, "d,s,t", MATCH_P_SMAR64 , MASK_P_SMAR64  , match_opcode, 0},
{"p.smsr64"     , 0, {"I",0}, "d,s,t", MATCH_P_SMSR64 , MASK_P_SMSR64  , match_opcode, 0},
{"p.umar64"     , 0, {"I",0}, "d,s,t", MATCH_P_UMAR64 , MASK_P_UMAR64  , match_opcode, 0},
{"p.umsr64"     , 0, {"I",0}, "d,s,t", MATCH_P_UMSR64 , MASK_P_UMSR64  , match_opcode, 0},
{"p.kmar64"     , 0, {"I",0}, "d,s,t", MATCH_P_KMAR64 , MASK_P_KMAR64  , match_opcode, 0},
{"p.kmsr64"     , 0, {"I",0}, "d,s,t", MATCH_P_KMSR64 , MASK_P_KMSR64  , match_opcode, 0},
{"p.ukmsr64"    , 0, {"I",0}, "d,s,t", MATCH_P_UKMSR64, MASK_P_UKMSR64 , match_opcode, 0},
{"p.ukmar64"    , 0, {"I",0}, "d,s,t", MATCH_P_UKMAR64, MASK_P_UKMAR64 , match_opcode, 0},
{"p.swap8"      , 0, {"I",0}, "d,s", MATCH_P_SWAP8  , MASK_P_SWAP8   , match_opcode, 0},
{"p.swap16"     , 0, {"I",0}, "d,s", MATCH_P_SWAP16 , MASK_P_SWAP16  , match_opcode, 0},
{"p.umul8"      , 0, {"I",0}, "d,s,t", MATCH_P_UMUL8  , MASK_P_UMUL8   , match_opcode, 0},
{"p.umulx8"     , 0, {"I",0}, "d,s,t", MATCH_P_UMULX8 , MASK_P_UMULX8  , match_opcode, 0},
{"p.umul16"     , 0, {"I",0}, "d,s,t", MATCH_P_UMUL16 , MASK_P_UMUL16  , match_opcode, 0},
{"p.umulx16"    , 0, {"I",0}, "d,s,t", MATCH_P_UMULX16, MASK_P_UMULX16 , match_opcode, 0},
{"p.add64"      , 0, {"I",0}, "d,s,t", MATCH_P_ADD64  , MASK_P_ADD64   , match_opcode, 0},
{"p.radd64"     , 0, {"I",0}, "d,s,t", MATCH_P_RADD64 , MASK_P_RADD64  , match_opcode, 0},
{"p.uradd64"    , 0, {"I",0}, "d,s,t", MATCH_P_URADD64, MASK_P_URADD64 , match_opcode, 0},
{"p.kadd64"     , 0, {"I",0}, "d,s,t", MATCH_P_KADD64 , MASK_P_KADD64  , match_opcode, 0},
{"p.ukadd64"    , 0, {"I",0}, "d,s,t", MATCH_P_UKADD64, MASK_P_UKADD64 , match_opcode, 0},
{"p.sub64"      , 0, {"I",0}, "d,s,t", MATCH_P_SUB64  , MASK_P_SUB64   , match_opcode, 0},
{"p.rsub64"     , 0, {"I",0}, "d,s,t", MATCH_P_RSUB64 , MASK_P_RSUB64  , match_opcode, 0},
{"p.ursub64"    , 0, {"I",0}, "d,s,t", MATCH_P_URSUB64, MASK_P_URSUB64 , match_opcode, 0},
{"p.ksub64"     , 0, {"I",0}, "d,s,t", MATCH_P_KSUB64 , MASK_P_KSUB64  , match_opcode, 0},
{"p.uksub64"    , 0, {"I",0}, "d,s,t", MATCH_P_UKSUB64, MASK_P_UKSUB64 , match_opcode, 0},
